<project xmlns="http://apache.org" 
         xmlns:xsi="http://w3.org" 
         xsi:schemaLocation="http://apache.org https://apache.org">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.internship</groupId>
  <artifactId>UserRegistrationAutomation</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <properties>
      <maven.compiler.source>11</maven.compiler.source>
      <maven.compiler.target>11</maven.compiler.target>
  </properties>

  <dependencies>
      <!-- Selenium WebDriver -->
      <dependency>
          <groupId>org.seleniumhq.selenium</groupId>
          <artifactId>selenium-java</artifactId>
          <version>4.12.1</version>
      </dependency>
      <!-- TestNG for Testing Framework -->
      <dependency>
          <groupId>org.testng</groupId>
          <artifactId>testng</artifactId>
          <version>7.8.0</version>
          <scope>test</scope>
      </dependency>
  </dependencies>
</project>